source "https://rubygems.org/"

gem 'rack', '~> 1.4.0'
gem 'rack-fiber_pool'
gem 'mysql2'
gem 'activerecord'
gem 'em-synchrony'
gem 'em-http-request'
gem 'grape'
gem 'goliath'
gem 'multi_json'
gem 'oj'
gem 'rabl'
gem 'standalone_migrations'
gem 'rake'
gem 'rspec'
gem 'pry'
gem 'rb-readline'
gem 'rails', '3.2.11'
